services:
  _defaults:
    autowire: true
    public: true

  Danilovl\HashidsBundle\Service\HashidsService:
    arguments:
      - '%danilovl.hashids.salt%'
      - '%danilovl.hashids.min_hash_length%'
      - '%danilovl.hashids.alphabet%'

  Danilovl\HashidsBundle\Interfaces\HashidsServiceInterface: '@Danilovl\HashidsBundle\Service\HashidsService'

  Danilovl\HashidsBundle\ParamConverter\HashidsParamConverter:
    arguments:
      $enable: '%danilovl.hashids.enable_param_converter%'
    tags:
      - { name: controller.argument_value_resolver, priority: 222 }
