services:
  _defaults:
    autowire: true
    public: true

  Danilovl\HashidsBundle\Service\HashidsService:
    arguments:
      - '%danilovl.hashids.salt%'
      - '%danilovl.hashids.min_hash_length%'
      - '%danilovl.hashids.alphabet%'

  Danilovl\HashidsBundle\Interfaces\HashidsServiceInterface: '@Danilovl\HashidsBundle\Service\HashidsService'

  Danilovl\HashidsBundle\ParamConverter\HashidsParamConverter:
    arguments:
      $continueNextConverter: '%danilovl.hashids.continue_next_converter%'
    tags:
      - { name: request.param_converter, converter: danilovl.hashids_param_converter, priority: 1 }
