services:
  danilovl.hashids:
    class: Danilovl\HashidsBundle\Services\HashidsService
    arguments:
      - '%danilovl.hashids.salt%'
      - '%danilovl.hashids.min_hash_length%'
      - '%danilovl.hashids.alphabet%'
    autowire: true
    public: true

  Danilovl\HashidsBundle\Services\HashidsService: '@danilovl.hashids'

  danilovl.hashids_param_converter:
    class: Danilovl\HashidsBundle\ParamConverter\HashidsParamConverter
    arguments:
      $passThrough: '%danilovl.hashids.pass_through%'
    autowire: true
    public: true
    tags:
      - { name: request.param_converter, converter: danilovl.hashids_param_converter, priority: 1 }

  Danilovl\HashidsBundle\ParamConverter\HashidsParamConverter: '@danilovl.hashids_param_converter'