name: Phpunit

on:
  - push
  - workflow_dispatch

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          apt-update && apt-get install libgmp-dev && docker-php-ext-install gmp
          composer install

      - name: Run tests
        run: vendor/bin/phpunit tests
